### ISSUE TITLE
Extensibility, not

### ISSUE THREAD

**Issue by martinthomson** [jeremyroman/http-no-vary-search#6]
> The dictionary must only contain entries whose keys are one of key-order, params, except.

If this is a MUST (is it?) then this will make it impossible to extend the field semantics.  An analysis of why this is acceptable is probably wise.

Note: I don't think that you need to establish an IANA registry for keys or anything like that.  This is a self-contained proposal that doesn't _need_ extensibility to function.  However, it would be good to establish clear rules for what an implementation does when an extension is present.  Right now, it seems to be that it completely disables the special logic that this draft introduces.  That seems wrong to me.  It would be more robust to ignore keys that are not supported.

**Comment by jeremyroman** [comment]
/cc @domenic (who wrote this precise wording)

> If this is a MUST (is it?) then this will make it impossible to extend the field semantics. An analysis of why this is acceptable is probably wise.

I'm not personally very familiar with how (in IETF) authoring conformance requirements bind future versions of a specification, or other documents, to extend it. The intent here, as I understand it, is simply to declare to authors that this document does not define the behavior of any field values which include other keys -- and an author using additional keys would need to be in conformance with some other, newer, document.

> Right now, it seems to be that it completely disables the special logic that this draft introduces. That seems wrong to me. It would be more robust to ignore keys that are not supported.

I'm not certain that is the case, but am open to discussing. It seems to me that future extensions might:

1. Make two responses match, which previously did not. (e.g., a new `key-ascii-case` token, which treated query param keys as case-insensitive)
2. Make two responses not match, which previous did. (e.g., a new `respect-exact-values` token, which required values for query params not ignored to match byte-wise, and not treat `+` and `%20`, or `a` and `%41`, as equivalent)
3. Some combination of the previous two.

For extensions of the first type, I agree, ignoring unrecognized keys is more robust in that it lets authors get as close to the intended meaning as possible within the client's support.

For extensions of the second or third type, though, ignoring unrecognized keys could result in a cache producing an erroneous cache hit – and a user seeing an incorrect resource.

Since the key is by definition unknown at the time this specification is written, even if most extensions would be of the first type it seems safer to assume that some extensions might be of the second or third type, and the risk of incorrect cache behavior might make such an extension dangerous to adopt if unrecognized parameters are ignored by earlier clients.

There might be ways to sidestep this, like some way of marking which extension parameters should be ignored if unknown, or giving HTTP some better feature detection mechanism (but that's an enormous challenge considering the presence of proxies and caches), but none seem an obvious win to me.

**Comment by martinthomson** [comment]
That seems like a good analysis.  My conjecture (take that for what it is), is that having any extension be *more* greedy (matching more URLs) is the most useful path to take.  Your case-folding example seems like it is more reasonable than any attempt to tighten up.

Is it possible for the other case to specify a backward-compatible exact-matching.  Maybe by using `params` in the least permissive mode, with a parallel `exact-params` parameter?

**Comment by domenic** [comment]
I'm not sure I understand the concern here. If we add new options, we'll publish a new specification that will supersede this one, and conformance with the old one won't matter.

**Comment by martinthomson** [comment]
@domenic, what you specify here will determine to a large extent what options you have when defining the new specification.  It pays to think about what might happen at that time.  Defining new parameters is clearly one of the possible paths available, but the present specification effectively causes the field to be ignored if a client receives a parameter they don't understand.  That's safe, but does it create the set up the right conditions for evolving the specification later?

**Comment by jeremyroman** [comment]
(I'm assuming that how the specification directs implementations to behave on unknown input matters here more than the author conformance requirements.)

Is there particular good/bad experiences with past HTTP header fields that should guide us here? At the moment it seems we're basically up to abstract conjecture.

I agree that ignoring unrecognized things (details TBD) makes it easier to roll out use of extensions in the future, at the cost of constraining those extensions (unless we add complexity to mitigate that), and that we could probably make that change safely at this point if everyone agreed (what is the best process for that?) this was a worthwhile tradeoff to make.

**Comment by martinthomson** [comment]
A good number of fields already work the same way, with considerable success.  Offhand, that includes Cache-Control, Content-Security-Policy, and Permissions-Policy.
